// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text string `json:"text"`
}

type Query struct {
}

type Todo struct {
	ID      string  `json:"id"`
	Text    string  `json:"text"`
	Summery *string `json:"summery,omitempty"`
	Done    bool    `json:"done"`
}

type UpdateTodo struct {
	Text *string `json:"text,omitempty"`
}

type User struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Designation string `json:"designation"`
	Department  string `json:"department"`
}
